### ISSUE TITLE
Game crashes while eating nuts

### ISSUE THREAD

**Issue by seaseii** [DakotaPride/create-garnished#1]
After testing, this bug can reproduce stably. Eating this mod's food multiple times (At least twice) can cause the game to crash

(After testing, eating sugary food after eating ungarnished food may cause the game to crash)

Zip contains the output logs of the launcher before the game crashes, in-game logs, version JSON files, startup scripts (. bat files), and crash files

Test used:
Minecraft-1.19.2
create-Fabric-0.5.1-b
garnished-0.4.1
jei-fabric-11.6.0.1016
owo-lib-0.9.3
fabric-api-0.76.0
wthit-fabric-5.16.2
[error.zip](https://github.com/DakotaPride/create-garnished/files/12258511/error.zip)

**Comment by DakotaPride** [comment]
Apologies for the long wait, I've been sick for the past 2ish days and haven't been at my computer for that duration. Thank you for your patience and understanding!

Are you able to provide any additional details regarding this issue? A minimal list of some potentially helpful details is listed below:

Regarding the first (and partially the second) issue mentioned in this report, are you eating peanuts, walnuts, cashews, etc.?
How often do these issues occur? And, if so, are you still experiencing these errors?
During either of these issues, are you able to record the replication process, in order to properly assess the issue and pinpoint where the error exactly lies?

In the meantime, I will be going through the programming of the mod and see if I can find the error myself. Again, thank you for your patience regarding this issue!

**Comment by DakotaPride** [comment]
A semi-temporary build has been posted onto Modrinth that hopefully fixes your issue. If the error does persist however, please come back to this report and say so (do not create another report for the same issue, otherwise you will be directed back to this issue report for further discussion)

Fabric: https://modrinth.com/mod/create-garnished/version/16E4kz7z

**Comment by seaseii** [comment]
OK,I'll try again

**Comment by seaseii** [comment]
At present, it seems that the problem has been resolved，thx
