### ISSUE TITLE
Falling Leaves if paired with "Leaves Us In Peace" Mod

### ISSUE THREAD

**Issue by mxKeaton** [DakotaPride/create-garnished#11]
Playing on 1.20.1 with the newest version of Garnished and Leaves Us in Peace.

All spawned nut trees immideatly drop their nuts. Might also occur with similiar mods like Leaves Be Gone.

**Comment by DakotaPride** [comment]
It seems to be an issue with how "Leaves Us In Peace" handles destroying the leaves, as when testing, "Leaves Be Gone" worked perfectly fine and didn't exhibit the same behaviour. I'd suggest potentially bringing this issue to the "Leaves Us In Peace" developer, or switching from "Leaves Us In Peace" to "Leaves Be Gone." I'll continue to look into it for now, and let me know if any other issues arise or if you've found more information regarding your problem so that I can take the proper steps to fix it. Thank you for your understanding and patience!

**Comment by mxKeaton** [comment]
I disabled the "match leave types" setting in the config. This fixes the issue, but gets rid of one of Leaves Be Gone's features. The only associated leaves of the tree decay on break. Will keep it like this for now.

Thanks for looking into it! I will post another issue soon
