### ISSUE TITLE
Issues with regular create tree farm

### ISSUE THREAD

**Issue by mxKeaton** [DakotaPride/create-garnished#12]
There are multiple issues that don't really make sense to me.
Whenever a nut tree grows it destroys the grass block below it. This breaks regular tree farms, but is still fixable with some dirt deplayers.
But even worse and unfixable, the trees do not drop any nuts or logs when cut by a saw. The only thing that drops are regular saplings.

Is this an issue on my end? Maybe an imcompatibility with another mod.

Here is a small [showcase video](https://drive.google.com/file/d/174Fq9E0lrjyHd7FvUKJ-lLPL7Le3EjSg/view?usp=sharing).
I forgot to turn off HDR, that is why it is so dark

**Comment by DakotaPride** [comment]
Are you playing a modpack of some kind? If so, please provide a modlist for proper testing of the issue. I am unsure as to what would even be causing this, especially considering that using Create: Garnished by itself (alongside dependencies of course) doesn't show the results above.

A few more things that I'd suggest, just in case:
If you are using an older version (any version prior to v0.8 for either 1.19.2 or 1.20), please update to v0.8. The issue may have been fixed upon release, or may not have.
What MC version are you using and what loader? I can, of course, go into the individual project and search for the issue manually. But providing this information makes the process easier and allows for the issue to be fixed swiftly so that other content-related features and issues can be implemented/solved.

Apologies for the inconvenience, and thank you for your understanding and patience regarding this issue!

**Comment by DakotaPride** [comment]
This issue has been marked as inactive. If you are still experiencing the issue, please refer to the previous comment made. Otherwise, feel free to ignore this message.
